In [2]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import requests

In [3]:
url = "https://raw.githubusercontent.com/karpathy/makemore/master/names.txt"
words = requests.get(url).text.splitlines()

print(words[:10])
len(words)

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia', 'harper', 'evelyn']


32033

In [4]:
enc = []
for w in words:
    enc.append([ord(c) - ord('a') for c in w])

print(enc[:3])

[[4, 12, 12, 0], [14, 11, 8, 21, 8, 0], [0, 21, 0]]


In [5]:
N = torch.zeros(4, 27)


In [6]:
print(words[0])
print(enc[0])
w = enc[0]
for i in range(len(w)):
    N[i][w[i]] = 1
N

emma
[4, 12, 12, 0]


tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
W = torch.randn((27, 27), requires_grad=True)
N.shape

torch.Size([4, 27])

In [8]:
xenc = F.one_hot(torch.tensor(enc[0]), num_classes=27).float()
ts = []
for i in range(1, len(enc[0])):
    ts.append(enc[0][i])
ts.append(26)
# target = F.one_hot(torch.tensor(ts), num_classes=27).float()
logits = xenc @ W
logits

tensor([[ 2.1656, -1.0264,  0.7512, -1.3100,  0.5423,  0.3563,  0.7094, -0.0755,
          0.8350,  0.2065, -0.7769,  0.0508,  0.1795,  1.4944, -1.1080,  1.6441,
         -0.7106, -0.7075, -0.9702,  1.8829, -0.7367,  0.5960, -1.0450,  1.2615,
          2.0230,  0.6695, -0.6299],
        [ 0.7119,  1.1021,  1.1439, -1.3056,  0.1826,  0.4812, -0.0313, -2.2584,
          0.6892,  0.4893,  0.3939, -1.7944, -0.8927, -0.2947,  0.1638, -0.4288,
          0.7467, -0.4198,  0.2023, -1.7016, -1.6666, -0.4460, -0.2084, -0.1025,
         -0.7351, -0.9310,  0.6727],
        [ 0.7119,  1.1021,  1.1439, -1.3056,  0.1826,  0.4812, -0.0313, -2.2584,
          0.6892,  0.4893,  0.3939, -1.7944, -0.8927, -0.2947,  0.1638, -0.4288,
          0.7467, -0.4198,  0.2023, -1.7016, -1.6666, -0.4460, -0.2084, -0.1025,
         -0.7351, -0.9310,  0.6727],
        [-0.8081,  1.2526,  1.6548, -0.6522,  0.8723, -0.2414, -0.1766, -0.4230,
         -0.2388, -0.1724,  0.3866,  0.2258, -0.3703,  0.6737,  1.1094,  0.3421

In [9]:
target

NameError: name 'target' is not defined

In [ ]:
count = logits.exp()
count
P = count/count.sum(1, keepdim=True)
P

NameError: name 'logits' is not defined

In [ ]:
P[0].sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [ ]:
loss = -P[torch.arange(4), ts].log().mean()
loss


tensor(3.2809, grad_fn=<NegBackward0>)

In [ ]:
loss.backward()

In [ ]:
#opt

W.data += -1 * W.grad
W.grad.zero_()

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
      