In [190]:
import torch
import torch.nn.functional as F
import matplotlib.pyplot as plt
import requests

In [191]:
url = "https://raw.githubusercontent.com/karpathy/makemore/master/names.txt"
words = requests.get(url).text.splitlines()

print(words[:10])
len(words)

['emma', 'olivia', 'ava', 'isabella', 'sophia', 'charlotte', 'mia', 'amelia', 'harper', 'evelyn']


32033

In [192]:
enc = []
for w in words:
    enc.append([ord(c) - ord('a') for c in w])

print(enc[:3])

[[4, 12, 12, 0], [14, 11, 8, 21, 8, 0], [0, 21, 0]]


In [193]:
N = torch.zeros(4, 27)


In [194]:
print(words[0])
print(enc[0])
w = enc[0]
for i in range(len(w)):
    N[i][w[i]] = 1
N

emma
[4, 12, 12, 0]


tensor([[0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [195]:
W = torch.randn((27, 27), requires_grad=True)
N.shape

torch.Size([4, 27])

In [ ]:
xenc = F.one_hot(torch.tensor(enc[0]), num_classes=27).float()
ts = []
for i in range(1, len(enc[0])):
    ts.append(enc[0][i])
ts.append(26)
# target = F.one_hot(torch.tensor(ts), num_classes=27).float()
logits = xenc @ W
logits

tensor([[ 7.5946e-01,  8.5077e-02, -3.0320e-01, -9.5861e-02, -3.4128e-01,
          4.3411e-01, -2.6788e-01,  7.0636e-01,  3.0966e-01,  3.5218e-01,
          1.8692e+00,  1.8838e-01, -9.5163e-01, -6.3636e-01, -1.6557e+00,
         -1.0719e+00,  7.6392e-01, -1.4141e+00,  1.7412e+00,  6.8125e-01,
          2.0937e-02, -1.0404e-01,  1.1038e+00, -2.4764e-01, -1.3431e+00,
         -2.2097e-02, -1.6543e+00],
        [ 1.5297e+00, -2.2773e-01, -1.6372e+00, -7.7673e-01, -2.1582e+00,
          6.4264e-01,  1.0595e+00, -6.3124e-01, -1.6671e+00, -6.9117e-01,
          9.5867e-01, -2.8544e-02, -1.0677e+00, -1.5738e-01, -1.6358e+00,
         -9.4022e-01,  2.4356e-01, -7.6174e-01,  1.1937e+00,  3.5303e-01,
         -2.6722e-01, -4.0890e-01, -1.8951e+00, -2.2749e+00, -4.8621e-01,
         -4.7226e-01, -1.6788e-01],
        [ 1.5297e+00, -2.2773e-01, -1.6372e+00, -7.7673e-01, -2.1582e+00,
          6.4264e-01,  1.0595e+00, -6.3124e-01, -1.6671e+00, -6.9117e-01,
          9.5867e-01, -2.8544e-02, -1.06

In [233]:
target

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [234]:
count = logits.exp()
P = count/count.sum(1, keepdim=True)
P

tensor([[0.0547, 0.0279, 0.0189, 0.0233, 0.0182, 0.0395, 0.0196, 0.0519, 0.0349,
         0.0364, 0.1660, 0.0309, 0.0099, 0.0135, 0.0049, 0.0088, 0.0550, 0.0062,
         0.1460, 0.0506, 0.0261, 0.0231, 0.0772, 0.0200, 0.0067, 0.0250, 0.0049],
        [0.1661, 0.0287, 0.0070, 0.0166, 0.0042, 0.0684, 0.1038, 0.0191, 0.0068,
         0.0180, 0.0939, 0.0350, 0.0124, 0.0307, 0.0070, 0.0141, 0.0459, 0.0168,
         0.1187, 0.0512, 0.0275, 0.0239, 0.0054, 0.0037, 0.0221, 0.0224, 0.0304],
        [0.1661, 0.0287, 0.0070, 0.0166, 0.0042, 0.0684, 0.1038, 0.0191, 0.0068,
         0.0180, 0.0939, 0.0350, 0.0124, 0.0307, 0.0070, 0.0141, 0.0459, 0.0168,
         0.1187, 0.0512, 0.0275, 0.0239, 0.0054, 0.0037, 0.0221, 0.0224, 0.0304],
        [0.0213, 0.0317, 0.0229, 0.0089, 0.0289, 0.0318, 0.0181, 0.0050, 0.0441,
         0.0384, 0.0740, 0.0256, 0.0226, 0.0368, 0.0088, 0.0124, 0.0025, 0.0516,
         0.0528, 0.0193, 0.0304, 0.0099, 0.0677, 0.0870, 0.1217, 0.0276, 0.0983]],
       grad_fn=<DivBack

In [235]:
P[0].sum()

tensor(1.0000, grad_fn=<SumBackward0>)

In [236]:
loss = -P[torch.arange(4), ts].log().mean()
loss


tensor(3.2809, grad_fn=<NegBackward0>)

In [237]:
loss.backward()

In [238]:
#opt

W.data += -1 * W.grad
W.grad.zero_()

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
      